# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.106</version>
#    <timestamp>2026-06-30T08:06:59.282Z</timestamp>
#    <hash>bf0a999a0a7d0a91</hash>
# </meta>

forge:
  - "/^forge$/m"
neoforge:
  - "/^neoforge$/m"

1.21.x:
  - "/^1.21$/m"
1.20.x:
  - "/^1.20$/m"
