# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>0.0.0-dev</version>
#    <timestamp>2026-03-03T15:28:13.977Z</timestamp>
# </meta>

forge:
  - "forge"
neoforge:
  - "neoforge"

1.21:
  - "1.21"
1.20:
  - "1.20"
1.19:
  - "1.19"
1.18:
  - "1.18"
