# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.60</version>
#    <timestamp>2026-05-13T07:26:12.811Z</timestamp>
#    <hash>bf0a999a0a7d0a91</hash>
# </meta>

forge:
  - "/^forge$/m"
neoforge:
  - "/^neoforge$/m"

1.21.x:
  - "/^1.21$/m"
1.20.x:
  - "/^1.20$/m"
