# Project
mod_version=0.0.0-dev
mod_name=Oreganized
mod_author=Team Galena
mod_id=oreganized

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# NeoForge
neoforge_version=21.1.248

# Publishing
release_type=release
maven_group=dev.galena
repository=teamgalena/oreganized
modrinth_project_id=2FJutzEL
curseforge_project_id=769203
