# Project
mod_version=0.0.0-dev
mod_name=Oreganized Carcinogenius
mod_author=Team Galena
mod_id=oreganized_carcinogenius
mod_version_suffix=carcinogenius

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.21.1
parchment_version=2024.11.17

# Forge
neoforge_version=21.1.152

# Other Dependencies
blueprint_version=8.0.5
jei_version=19.21.0.247

jade_version=iku9fmp8
oreganized_version=5.0.0
multikulti_version=37-SNAPSHOT

# Publishing
release_type=release
maven_group=dev.galena
repository=teamgalena/oreganized
modrinth_project_id=1JyBUpOv
curseforge_project_id=1279957
