# Project
mod_version=0.0.0-dev
mod_name=Oreganized
mod_author=Team Galena
mod_id=oreganized_carcinogenius

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.20.1

# Forge
forge_version=47.3.10

# Mixin
mixin_version=0.8.5
mixin_extras_version=0.4.1

# Other Dependencies
blueprint_version=7.1.0
jei_version=15.20.0.106

farmersdelight_version=1.20.1-1.2.4
nethersdelight_version=MTDQhZd2
shieldexpansion_version=8mpKmudC
create_version=6.0.1-25
ponder_version=1.0.43
supplementaries_version=bHRxbeqq
scannable_version=2FlwUOgm
architectury_version=tBWqtdBO
moonlight_lib_version=z4VYWtIk
dye_depot_version=cdGlC270
jade_version=9gf6jOO0
galena_hats_version=1.0.0

# Publishing
release_type=release
maven_group=dev.galena
repository=teamgalena/oreganized
modrinth_project_id=
curseforge_project_id=
