modLoader="javafml"
loaderVersion="[47,)"
license="https://github.com/${repository}/blob/1.20.x/LICENSE.md"
issueTrackerURL="https://github.com/${repository}/issues/"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://api.modrinth.com/updates/oreganized/forge_updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/oreganized"
logoBlur=false
itemIcon="oreganized:asbestos_block"
configBackground="oreganized:textures/block/asbestos_block.png"
credits="Thanks to our wonderful Patreon members and those who help participate in discussions on our Discord server!"
authors="${mod_author}"
description='''
Addon for Oreganized that includes the asbestos content added for april fools in 2025
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="blueprint"
    mandatory=true
    versionRange="[7.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="oreganized"
    mandatory=true
    versionRange="[4.2.3,)"
    ordering="AFTER"
    side="BOTH"