[versions]
multikulti = "1.21.1-1.2.3"
jei = "19.21.0.247"

[libraries]
multikulti-datagen = { group = "com.possible-triangle", name = "multikulti-datagen-neoforge", version.ref = "multikulti" }

blueprint = { group = "com.teamabnormals", name = "blueprint", version = "1.21.1-8.1.0" }

galena-hats = { "group" = "dev.galena", name = "hats-neoforge", version = "1.21.1-1.2.4" }

dye-depot = { group = "com.ninni.dye_depot", name = "dye_depot", version = "1.21.1-2.0.0-neoforge" }

create = { group = "com.simibubi.create", name = "create-1.21.1", version = "6.0.6-99" }

jei-common-api = { group = "mezz.jei", name = "jei-1.21.1-common-api", version.ref = "jei" }
jei-neoforge-api = { group = "mezz.jei", name = "jei-1.21.1-neoforge-api", version.ref = "jei" }
jei-neoforge = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version.ref = "jei" }
