# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.18</version>
#    <timestamp>2026-03-21T06:23:58.910Z</timestamp>
# </meta>

name: Feature Request
description: Suggest a feature
labels: ["enhancement"]

body:
  - type: textarea
    id: idea
    attributes:
      label: Describe the feature you have in mind.
      placeholder: So I was think about...
    validations:
      required: true

  - type: textarea
    id: problem-solving
    attributes:
      label: Does this solve a particular problem?
      placeholder: Yes, it balances...
    validations:
      required: false
