name = "Oreganized Dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb0d94f8c3f9f00c1b0fcf4fc08f650510dab917d3008ee8f940beea102cbc1c"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
